# Form implementation generated from reading ui file 'bot_UI.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1376, 695)
        MainWindow.setStyleSheet("background-color: rgb(42, 42, 42)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.get_servers_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(10)
        self.get_servers_button.setFont(font)
        self.get_servers_button.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(204, 120, 50);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(204, 120, 50)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(237, 131, 43);\n"
"    background-color: rgb(237, 131, 43)\n"
"}")
        self.get_servers_button.setObjectName("get_servers_button")
        self.verticalLayout.addWidget(self.get_servers_button)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(25, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0, 0)")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_text.setContentsMargins(-1, 0, -1, 10)
        self.verticalLayout_text.setObjectName("verticalLayout_text")
        self.verticalLayout_4.addLayout(self.verticalLayout_text)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0, 0)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_voice = QtWidgets.QVBoxLayout()
        self.verticalLayout_voice.setContentsMargins(-1, 0, -1, 10)
        self.verticalLayout_voice.setObjectName("verticalLayout_voice")
        self.verticalLayout_4.addLayout(self.verticalLayout_voice)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"border-radius: 20px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 858, 586))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"border-radius: 20px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_messages = QtWidgets.QVBoxLayout()
        self.verticalLayout_messages.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_messages.setObjectName("verticalLayout_messages")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_messages.addItem(spacerItem2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(18, 134, 12)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 10px")
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.verticalLayout_messages.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_messages)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalScrollBar.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.verticalScrollBar.setFont(font)
        self.verticalScrollBar.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(204, 120, 50);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(237, 131, 43);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    background: rgb(38, 38, 38);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background: rgb(38, 38, 38);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: 1px solid rgb(38, 38, 38);\n"
"    background-color: rgb(38, 38, 38);\n"
"    border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientations.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_5.addWidget(self.verticalScrollBar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(99999, 10, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(66, 66, 66);\n"
"    border-radius: 12px;\n"
"    background-color: rgb(66, 66, 66);\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setEnabled(True)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(225, 0))
        self.scrollArea_2.setStyleSheet("border: none;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 225, 675))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 10, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_8.addItem(spacerItem4)
        self.verticalLayout_users = QtWidgets.QVBoxLayout()
        self.verticalLayout_users.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_users.setObjectName("verticalLayout_users")
        self.verticalLayout_8.addLayout(self.verticalLayout_users)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_3)
        self.verticalScrollBar_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.verticalScrollBar_2.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(204, 120, 50);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(237, 131, 43);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    background: rgb(38, 38, 38);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background: rgb(38, 38, 38);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: 1px solid rgb(38, 38, 38);\n"
"    background-color: rgb(38, 38, 38);\n"
"    border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}")
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Orientations.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_8.addWidget(self.verticalScrollBar_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discord 2.0"))
        self.get_servers_button.setText(_translate("MainWindow", "Get Servers"))
        self.label.setText(_translate("MainWindow", " ⌵ Text Channels"))
        self.label_2.setText(_translate("MainWindow", " ⌵ Voice Channels"))
        self.label_3.setText(_translate("MainWindow", "Fuguetero"))
        self.label_4.setText(_translate("MainWindow", "Teste do discord 2.0"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Send Message..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
